name: cmake_build
	
	on:
	  #push:
	  #  branches: [ master ]
	  workflow_dispatch:
	
	jobs:
	  build:
	    runs-on: ubuntu-latest
	    
	    steps:
	    - name: checkout
	      uses: actions/checkout@v3
	    
	    - name: Build a *formatter* library
	      run: |
	        cmake -H. -B_build
	        cmake --build _build
	      shell: bash
	      working-directory: lab_4/formatter_lib
	      
	    - name: Build a *formatter_ex* library
	      run: |
	        cmake -H. -B_build
	        cmake --build _build
	      shell: bash
	      working-directory: lab4/formatter_ex_lib
	      
	    - name: Build a *hello_world* application
	      run: |
	        cmake -H. -B_build
	        cmake --build _build
	      shell: bash
	      working-directory: lab4/hello_world_application
	      
	      
	    - name: Build a *solver* application
	      run: |
	        cmake -H. -B_build
	        cmake --build _build
	      shell: bash
	      working-directory: lab4/solver_application
